$ANSIBLE_VAULT;1.1;AES256
65386436613964343537343262646161623731303037616136363535303434323836633738616533
3634656564623036323363646532336530363066373634310a656264396535326232626432363332
35376338306365383731326166636262356261343339366362356338303639656439333561373637
6566363533653336360a323765316630306430306233373031616563333934373434663433313063
61363666343237363365396464616233373266306333303465343062316265343164396231623734
38653666613063373662303166353662633039373430633830646665383630393838396564626239
63343336656232343137336666383564373630383437653436643061316266303663333030623536
31646233363330613330
